### PR TITLE
Update model-lsa.js

### PR DESCRIPTION
**Pull request by PillePiletti**
Hi Greg,
do you have to approve the changes I made?
I'd like to delete and upload files.
Greetings,
Philipp

### CODE REVIEW

**Comment by GregVes** [comment]
Hi Philipp,

The best is that you update the pictures that are in the assets folder still in your "patch-3" branch. I'll then be notified of the change right here, and make the merge into the master.

Also when checking your branchm, we can see that pictures are broken (https://deploy-preview-27--clothes-configurator.netlify.com/). This is an expected behavior as the mapping model-lsa and pictures names in assets folder is broken with the changed you made in model-lsa. So keep in mind in mind that pictures you'll upload in assets should have a consistent prefix/suffix in line with your changes in model-lsa.

For example, you exchanged "neck-" with "gurt-". This means that in the asset, you should now put "gurt-" prefix to the pictures who have "neck-". And the same goes for "base-" that you should turn into "lsa-".

If you have any problem dealing with this, just let me know, I can do it for you. I'll just need you to send me the pictures.

**Comment by PillePiletti** [comment]
Hi Greg,
here are the pictures, that I wanted to upload.
I changed the names because of the „Groß-/Kleinschreibung“.
Like I see, it works perfectly.
Could you please upload the pictures.
Thank you, greetings,
Philipp

**Comment by PillePiletti** [comment]
Hi Greg,
now I understood. I can make changes in my „own“ branch (patch-3).
I tried to upload a file (lsa-kurz.png), but I can’t find it in my assets folder. Even the file finder doesn’t find it.
Do you know, whats wrong?
Greetings, Philipp

**Comment by GregVes** [comment]
Ciao Philipp,

To upload a picture, you need to: 
- go to your repo page (https://github.com/PillePiletti/clothes-configurator)
- click on "assets" folder
- click on "upload files" tab
- drag the files you want to upload
- click on "commit changes" green box (bottom of the page)

To delete a picture instead, still in "assets" folder:
- click on the picture you'd like to delete
- then you can see a garbage icon, click on it to delete the file


But I can also do all for you. You just need to make me a collaborator of your forked repository...

- go to the fork repo page: https://github.com/PillePiletti/clothes-configurator
- click on "settings" tab in the menu 
- then click on "collaborators" on the right side bar
- in the search bar, look for "GregVes" and hit "add collaborator"

.. and send me the pictures so that I can upload them on "patch-3" branch and then merge to the master: 
- WeTransfer to vespasiengregory@gmail.com

**Comment by PillePiletti** [comment]
Hi Greg,
somehow I wasn’t able to upload lsa-kurz as a png.
Now I created a new branch (PillePiletti-patch-3) and uploaded and deleted all the files.
It would be great, if I had a preview to this file, so I could see the new files in the browser.
Greetings and thank you!
Philipp

**Comment by GregVes** [comment]
Hey Philipp,

I created a local branch from your PillePiletti-patch-3 and fixed the issues with the file names. I need you to add me as a collaborator so that I can push my local branch here on github for you to see.

Nevertheless, the filters we applied previously are now giving the wrong colors, you'll see what I mean when I'll be able to push my local branch.

**Comment by PillePiletti** [comment]
Hi Greg,
I’ll try to add you as a collaborator.
https://github.com/PillePiletti/clothes-configurator/invitations

I know about the color „problem“.
I changed the basic color, because it’s much easier to reduce saturation with the browser tools than to change the colors the other way around. When I see the configurator in the browser, I’m gonna change the color settings.

Greetings,
Philipp

**Comment by PillePiletti** [comment]
Dear Greg,
today I’ve tried this and that.
Somehow I can change everything in the patch-3 folder, changes are visible in the configurator.
So for me there are no problems in the moment.
(There are a lot, but not with github).
I have to change the png-files, because of the transparency and so on - much to do.
Thanks for your help.
Greetings,
Philipp

**Comment by GregVes** [comment]
Hello Philipp,

I just saw that you managed all by yourself and that your branch is actually working (https://deploy-preview-27--clothes-configurator.netlify.com/). I think I can merge into the master.

Let me know where I can help you.

**Pull request merged**
